import { Account, RpcProvider, Contract, CallData, cairo } from 'starknet';
import dotenv from 'dotenv';

dotenv.config();

// Initialize Provider (Sepolia)
const provider = new RpcProvider({ 
    nodeUrl: process.env.STARKNET_RPC_URL || "https://starknet-sepolia.public.blastapi.io" 
});

// Initialize Account (Merchant Admin)
const merchantAddress = process.env.MERCHANT_ACCOUNT_ADDRESS || "";
const privateKey = process.env.MERCHANT_PRIVATE_KEY || "";
const contractAddress = process.env.CONTRACT_ADDRESS || "";

const account = new Account(provider, merchantAddress, privateKey);

// ABI snippet for the mint function (simplified for direct use)
// In a real setup, import the full JSON ABI generated by Scarb
const contractAbi = [
  {
    "type": "function",
    "name": "mint_passport",
    "inputs": [
      { "name": "recipient", "type": "core::starknet::contract_address::ContractAddress" },
      { "name": "token_id", "type": "core::integer::u256" },
      { "name": "product_hash", "type": "core::felt252" }
    ],
    "outputs": [],
    "state_mutability": "external"
  }
];

export class StarknetService {
    
    constructor() {
        if (!merchantAddress || !privateKey) {
            console.warn("⚠️ Starknet credentials missing in .env");
        }
    }

    /**
     * Mints a new Passport NFT to the merchant's address (as initial inventory)
     * @param tokenId Unique ID for the passport (e.g. hash of SKU + Serial)
     * @param productHash Metadata hash (IPFS hash or similar)
     */
    async mintPassport(tokenId: string, productHash: string) {
        try {
            console.log(`Minting TokenID: ${tokenId} with Hash: ${productHash}...`);

            // Connect to contract
            const contract = new Contract(contractAbi, contractAddress, provider);
            contract.connect(account);

            // Execute mint transaction
            // We mint to 'merchantAddress' first. The customer will 'claim' (transfer) it later.
            // Using cairo.uint256 to handle large numbers safely
            const tx = await contract.mint_passport(
                merchantAddress, 
                cairo.uint256(tokenId), 
                productHash
            );

            console.log("Transaction sent:", tx.transaction_hash);
            
            // Wait for transaction acceptance (optional, depends on UX speed requirements)
            await provider.waitForTransaction(tx.transaction_hash);
            console.log("Transaction confirmed on L2");

            return tx.transaction_hash;

        } catch (error) {
            console.error("Minting failed:", error);
            throw error;
        }
    }
}
